import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Talk2Book CMS",
  description: "CMS dashboard for managing travel products and content",
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< Updated upstream
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
=======
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
>>>>>>> Stashed changes
      >
        {children}
      </body>
    </html>
  );
}
